markdown: rdiscount
pygments: true
name: Coderetreat 中国, 编码功夫 | Coderetreat China, Coding Kung fu
description: Coderetreat 中国, 编码功夫 | Coderetreat China, Coding Kung fu
url: http://coderetreat-china.github.io/
